name: ExcelCoordinate workflow

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build
        # env: 
        #   PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
        shell: pwsh
        run: |
          Invoke-Build . 